ALTER TABLE events ADD COLUMN IF NOT EXISTS external_id VARCHAR(100);
ALTER TABLE events ADD COLUMN IF NOT EXISTS home_team VARCHAR(150);
ALTER TABLE events ADD COLUMN IF NOT EXISTS away_team VARCHAR(150);
ALTER TABLE events ADD COLUMN IF NOT EXISTS sport_name VARCHAR(100);